name: VPS Runner

on:
  workflow_dispatch:
    inputs:
      uptime:
        description: 'VPS uptime in hours (max 6)'
        required: false
        default: '6'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
    - name: Download binary
      run: |
        apt update

    - name: Keep VM alive with restart loop
      run: |
        UPTIME=${{ github.event.inputs.uptime }}
        END_TIME=$(( $(date +%s) + ($UPTIME * 3600) ))
        echo "Will keep running until: $(date -d @$END_TIME)"
        
        while [ $(date +%s) -lt $END_TIME ]; do
          echo "Attempting to run binary..."
          # Try to run the binary, but continue even if it fails
          ./px86 x86 || echo "Binary exited, continuing..."
          sleep 1
        done
        
        echo "Successfully completed $UPTIME hours"
